apiVersion: 1

deleteDatasources:
  - name: JSON API
    orgId: 1
  - name: Django API
    orgId: 1
  - name: Google Cloud Logging
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false

  - name: Django API
    type: yesoreyeram-infinity-datasource
    uid: json-api
    url: https://affordable-gadgets-backend-i2s6.onrender.com
    access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      httpHeaderName1: "Authorization"
      allowedHosts:
        - "https://affordable-gadgets-backend-i2s6.onrender.com"
    secureJsonData:
      httpHeaderValue1: "Token $__env{GF_JSON_API_TOKEN}"
