---
- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose-plugin
      - curl
    state: present
    update_cache: true
  when: docker_check.rc != 0 or common_force_docker_install | default(false)

- name: Enable Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create compose directory
  file:
    path: "{{ compose_root }}"
    state: directory
    mode: "0755"
