"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this should come from environment variable
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-z&id8l&gleealb7*wwh))7p#f2b#(ki)m1_otxm=+%gx!6001m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.1.6,192.168.1.28,192.168.1.77').split(',')
AUTH_USER_MODEL = 'inventory.User'


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'corsheaders',  # <--- ADDED: For CORS support (must be before django apps)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',  # <--- ADDED: Must be before 'cloudinary'
    'cloudinary',  # <--- ADDED: Cloudinary integration
    'rest_framework',
    'rest_framework.authtoken', # <--- ADDED: Required for TokenAuthentication
    'drf_spectacular',  # <--- ADDED: OpenAPI 3 schema generation
    'inventory',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <--- ADDED: Must be near top, before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'inventory.middleware.BrandContextMiddleware',  # Brand context middleware
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # 1. DEFAULT AUTHENTICATION: Prioritize Token for API clients
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', 
        'rest_framework.authentication.SessionAuthentication',
    ],

    # 2. DEFAULT PERMISSION CLASSES: Secure by default
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # 3. DEFAULT RENDERER:
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    
    # 4. PAGINATION:
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    
    # 5. OPENAPI SCHEMA: Use drf-spectacular for automatic schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads - Images, Videos)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Configuration
# Get credentials from environment variables or .env file
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
    # Optional: Set secure delivery
    'SECURE': True,
    # Optional: Set default resource type
    'RESOURCE_TYPE': 'auto',  # 'image', 'video', 'raw', or 'auto'
}

# Use Cloudinary for media files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Optional: Use Cloudinary for static files too (uncomment if desired)
# STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- drf-spectacular Configuration (OpenAPI 3 Schema Generation) ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'Inventory Management & E-commerce API',
    'VERSION': '1.0.0',
    'DESCRIPTION': '''
    Complete API specification for the Django-based Inventory Management and Sales system.
    DRF TokenAuthentication is used: clients must send `Authorization: Token <key>` for protected endpoints.
    ''',
    'SERVE_INCLUDE_SCHEMA': False,  # Don't include schema in Swagger UI
    'SCHEMA_PATH_PREFIX': '/api/inventory',  # Base path for all endpoints
    'COMPONENT_SPLIT_REQUEST': True,  # Split request/response schemas
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,  # Don't require read-only fields
    'AUTHENTICATION_WHITELIST': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'SERVERS': [
        {'url': '/api/inventory/', 'description': 'Inventory Management API'},
        {'url': '/api/v1/public/', 'description': 'Public E-commerce API'},
    ],
    'TAGS': [
        {'name': 'Account & Profile Management', 'description': 'User authentication and profile management'},
        {'name': 'Core Catalog & Inventory Management', 'description': 'Products, units, reports, and inventory operations'},
        {'name': 'Order & Sales Management', 'description': 'Orders, payments, and sales operations'},
        {'name': 'Discovery & Utility', 'description': 'Search, discovery, and utility endpoints'},
        {'name': 'Lookup Table Management', 'description': 'Colors, sources, promotion types, and other lookup tables'},
        {'name': 'Request Management', 'description': 'Leads, reservation requests, return requests'},
        {'name': 'Notifications', 'description': 'User notifications and alerts'},
    ],
    # Customize schema generation
    'SCHEMA_PATH_PREFIX_TRIM': True,  # Trim common prefix from paths
    'DEFAULT_GENERATOR_CLASS': 'drf_spectacular.generators.SchemaGenerator',
    'ENUM_NAME_OVERRIDES': {
        'OrderStatusEnum': 'inventory.models.Order.StatusChoices',
        'SaleStatusEnum': 'inventory.models.InventoryUnit.SaleStatusChoices',
    },
}

# --- Pesapal Configuration ---
# All Pesapal credentials must come from environment variables (no defaults)
PESAPAL_CONSUMER_KEY = os.environ.get('PESAPAL_CONSUMER_KEY', '')
PESAPAL_CONSUMER_SECRET = os.environ.get('PESAPAL_CONSUMER_SECRET', '')
PESAPAL_ENVIRONMENT = os.environ.get('PESAPAL_ENVIRONMENT', 'sandbox')  # Default to sandbox for safety
PESAPAL_CALLBACK_URL = os.environ.get('PESAPAL_CALLBACK_URL', '')
PESAPAL_IPN_URL = os.environ.get('PESAPAL_IPN_URL', '')
PESAPAL_NOTIFICATION_ID = os.environ.get('PESAPAL_NOTIFICATION_ID', '')
PESAPAL_API_TIMEOUT = int(os.environ.get('PESAPAL_API_TIMEOUT', '30'))
PESAPAL_MAX_RETRIES = int(os.environ.get('PESAPAL_MAX_RETRIES', '3'))
PESAPAL_RETRY_DELAY = int(os.environ.get('PESAPAL_RETRY_DELAY', '2'))
PESAPAL_LOG_PATH = os.environ.get('PESAPAL_LOG_PATH', '/tmp/pesapal_debug.log')

# --- Email Configuration ---
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# --- Twilio WhatsApp Configuration ---
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '')  # Format: whatsapp:+14155238886

# --- CORS Configuration (Development) ---
# Configure allowed origins for your frontend applications
# Update these when deploying to production with actual frontend URLs

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Create React App default port
    "http://localhost:3001",   # Next.js (if using different port)
    "http://localhost:3002",   # Alternative React App port
    "http://127.0.0.1:3000",   # Alternative localhost format for CRA
    "http://127.0.0.1:3001",   # Alternative localhost format for Next.js
    "http://127.0.0.1:3002",   # Alternative localhost format for CRA
    "http://192.168.1.6:3000",  # Local network IP for Next.js
    "http://192.168.1.6:3001",  # Local network IP alternative port
    "http://192.168.1.6:3002",  # Local network IP alternative port
    "http://192.168.1.28:3000",  # Local network IP for admin frontend
    "http://192.168.1.28:3001",  # Local network IP alternative port
    "http://192.168.1.28:3002",  # Local network IP for admin frontend (current)
    "http://192.168.1.77:3000",  # Local network IP for e-commerce frontend
    "http://192.168.1.77:3001",  # Local network IP alternative port
    "http://192.168.1.77:3002",  # Local network IP alternative port
]

# Allow credentials (cookies, authorization headers) if needed
CORS_ALLOW_CREDENTIALS = True

# Allow common headers your API uses
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # Required for Token Authentication (Authorization: Token <key>)
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-brand-code',  # Required for brand-based filtering
    'idempotency-key',  # Required for order idempotency
    'x-idempotency-key',  # Alternative idempotency key header
]

# Allow these HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Load production settings if DJANGO_ENV is set to 'production'
# This must be at the end to override development settings
if os.environ.get('DJANGO_ENV') == 'production':
    from .settings_production import *
