#!/usr/bin/env bash
# Write deploy/ansible/vars/generated_from_terraform.yml from terraform output.
# Usage (from deploy/terraform):
#   terraform apply -var-file=environments/staging.tfvars
#   ../ansible/scripts/generate_ansible_vars_from_terraform.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_VARS="${SCRIPT_DIR}/../vars/generated_from_terraform.yml"
TF_DIR="${SCRIPT_DIR}/../../terraform"

cd "${TF_DIR}"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform not found" >&2
  exit 1
fi

json="$(terraform output -json 2>/dev/null || true)"
if [[ -z "${json}" || "${json}" == "{}" ]]; then
  echo "No terraform outputs; run terraform apply first." >&2
  exit 1
fi

export TF_JSON="${json}"
python3 > "${ANSIBLE_VARS}" <<'PY'
import json, os
out = json.loads(os.environ["TF_JSON"])

def val(key):
    o = out.get(key)
    if o is None:
        return None
    return o.get("value")

lines = [
    "---",
    "# Generated by generate_ansible_vars_from_terraform.sh — do not edit by hand.",
    f"gcp_project_id: \"{val('project_id') or ''}\"",
    f"cloud_sql_private_ip: \"{val('cloud_sql_private_ip') or ''}\"",
    f"cloud_sql_connection_name: \"{val('cloud_sql_connection_name') or ''}\"",
    f"redis_host: \"{val('redis_host') or ''}\"",
    f"redis_port: {val('redis_port') or 6379}",
    f"redis_url: \"{val('redis_url') or ''}\"",
    f"artifact_registry_host: \"{val('artifact_registry_host') or ''}\"",
    f"api_lb_ip: \"{val('api_lb_ip') or ''}\"",
    f"shop_lb_ip: \"{val('shop_lb_ip') or ''}\"",
    f"admin_lb_ip: \"{val('admin_lb_ip') or ''}\"",
    f"api_mig_name: \"{val('api_mig_name') or ''}\"",
    f"shop_mig_name: \"{val('shop_mig_name') or ''}\"",
    f"admin_mig_name: \"{val('admin_mig_name') or ''}\"",
    f"deploy_config_bucket: \"{val('deploy_config_bucket') or ''}\"",
    f"bastion_name: \"{val('bastion_name') or ''}\"",
    f"tunnel_instance_name: \"{val('tunnel_instance_name') or ''}\"",
    f"gcp_zone: \"{val('zone') or 'us-central1-a'}\"",
]
print("\n".join(lines))
PY

echo "Wrote ${ANSIBLE_VARS}"
