global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'django'
    scrape_interval: 10s
    metrics_path: /metrics/
    static_configs:
      - targets:
          - '10.10.1.28:8000'
          - '10.10.1.29:8000'
          - '10.10.1.30:8000'
    # Relabel to add a `service` label
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'django-api'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
