# Generated by Django 5.2.7 on 2025-11-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_create_default_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrole',
            options={'ordering': ['display_name'], 'verbose_name': 'Admin Role', 'verbose_name_plural': 'Admin Roles'},
        ),
        migrations.AlterModelOptions(
            name='reservationrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Reservation Request', 'verbose_name_plural': 'Reservation Requests'},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Return Request', 'verbose_name_plural': 'Return Requests'},
        ),
        migrations.AlterModelOptions(
            name='unittransfer',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Unit Transfer', 'verbose_name_plural': 'Unit Transfers'},
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(choices=[('SP', 'Salesperson'), ('IM', 'Inventory Manager'), ('CC', 'Content Creator'), ('OM', 'Order Manager')], db_column='role_code', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who has reserved this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_units', to='inventory.admin'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RA', 'Reservation Approved'), ('RR', 'Reservation Rejected'), ('RE', 'Reservation Expired'), ('TA', 'Return Approved'), ('TR', 'Return Rejected'), ('FA', 'Transfer Approved'), ('FR', 'Transfer Rejected'), ('OC', 'Order Created'), ('UR', 'Unit Reserved'), ('RP', 'Request Pending Approval')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservation_requests', to='inventory.admin', verbose_name='Approving Inventory Manager'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='requesting_salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='inventory.admin', verbose_name='Requesting Salesperson'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_return_requests', to='inventory.admin', verbose_name='Approving Inventory Manager'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='inventory_units',
            field=models.ManyToManyField(related_name='return_requests', to='inventory.inventoryunit', verbose_name='Units to Return'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='requesting_salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='inventory.admin', verbose_name='Requesting Salesperson'),
        ),
        migrations.AlterField(
            model_name='unittransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='inventory.admin', verbose_name='Approving Inventory Manager'),
        ),
        migrations.AlterField(
            model_name='unittransfer',
            name='from_salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.admin', verbose_name='Current Salesperson'),
        ),
        migrations.AlterField(
            model_name='unittransfer',
            name='to_salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.admin', verbose_name='Target Salesperson'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='inventory_n_recipie_1f67b8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='inventory_n_recipie_8cacb8_idx'),
        ),
    ]
