# Generated by Django 5.2.7 on 2025-10-29 14:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_orderitem_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAcquisitionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SU', 'Supplier'), ('IM', 'Import Partner')], max_length=2)),
                ('name', models.CharField(help_text='Name of the company or contact person.', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Unit Acquisition Sources',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling price of the unit at the moment of order.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='N/A', help_text='e.g., Samsung, Apple, Dell', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='model_series',
            field=models.CharField(default='N/A', help_text='e.g., S series, Fold, XPS', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.customer', verbose_name='Review Creator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of this item bought in the order.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PH', 'Phone'), ('LT', 'Laptop'), ('TB', 'Tablet/iPad'), ('AC', 'Accessory')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='accessory',
            field=models.ForeignKey(limit_choices_to={'product_type': 'AC'}, on_delete=django.db.models.deletion.CASCADE, related_name='used_by_products', to='inventory.product', verbose_name='Accessory Item Template'),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='main_product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['PH', 'LT', 'TB']}, on_delete=django.db.models.deletion.CASCADE, related_name='product_accessories', to='inventory.product', verbose_name='Main Product Template'),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='required_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.product', verbose_name='Reviewed Product Template'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity is 1 for Phones/Laptops. Can be > 1 for Accessories/Bulk SKUs.')),
                ('condition', models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('P', 'Pre-owned'), ('D', 'Defective')], default='N', max_length=1)),
                ('source', models.CharField(choices=[('BB', 'Buyback (Customer)'), ('SU', 'External Supplier'), ('IM', 'External Import')], default='SU', max_length=2)),
                ('sale_status', models.CharField(choices=[('AV', 'Available'), ('SD', 'Sold'), ('RS', 'Reserved'), ('RT', 'Returned')], default='AV', max_length=2)),
                ('grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B')], max_length=1, null=True)),
                ('cost_of_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Internal Cost')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Selling Price')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imei', models.CharField(blank=True, help_text='IMEI for Phones/SIM-enabled Tablets', max_length=15, null=True, unique=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sim_enabled', models.BooleanField(default=False, verbose_name='Supports SIM/Cellular')),
                ('processor_details', models.CharField(blank=True, max_length=255)),
                ('date_sourced', models.DateField(blank=True, help_text='Date the unit was acquired', null=True)),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='inventory.product', verbose_name='Product Model/Template')),
                ('acquisition_source_details', models.ForeignKey(blank=True, help_text='Details for Supplier or Import source (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitacquisitionsource')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, help_text='The specific InventoryUnit sold (required for unique items like phones).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.inventoryunit', verbose_name='Stock Keeping Unit (SKU)'),
        ),
    ]
