# Generated by Django 5.2.7 on 2025-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_unitacquisitionsource_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link (URL or path) to a video review.', max_length=255, null=True, verbose_name='Review Video Link'),
        ),
    ]
