# Generated by Django 5.2.7 on 2025-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_adminrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='Mark product as discontinued (no longer in catalog)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.IntegerField(blank=True, help_text='Minimum stock level before triggering low stock alert', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(blank=True, help_text='Stock level at which to reorder/restock', null=True),
        ),
    ]
