# Generated by Django 5.2.7 on 2025-11-03 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_product_is_discontinued_product_min_stock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CR', 'Create'), ('UP', 'Update'), ('DL', 'Delete'), ('AP', 'Approve'), ('RJ', 'Reject'), ('RS', 'Reserve'), ('RL', 'Release'), ('TR', 'Transfer'), ('AR', 'Archive'), ('BU', 'Bulk Update'), ('PC', 'Price Change'), ('SC', 'Status Change')], max_length=2)),
                ('model_name', models.CharField(help_text='Name of the model affected', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the affected object')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=255)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state (for updates)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state (for creates/updates)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='inventory_a_timesta_179bee_idx'), models.Index(fields=['model_name', '-timestamp'], name='inventory_a_model_n_6c76d0_idx')],
            },
        ),
    ]
