# Generated by Django 5.2.7 on 2025-10-31 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_product_image_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryunit',
            name='quantity',
        ),
        migrations.CreateModel(
            name='InventoryUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_photos/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryunit')),
            ],
        ),
    ]
