# Generated by Django 5.2.7 on 2025-11-05 06:21

from django.db import migrations, models, connection
from django.utils.text import slugify


def generate_slugs_for_products(apps, schema_editor):
    """Generate unique slugs for existing products."""
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if not product.slug and product.product_name:
            base_slug = slugify(product.product_name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save(update_fields=['slug'])


def reverse_generate_slugs(apps, schema_editor):
    """Reverse migration - clear slugs."""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.all().update(slug='')


def drop_duplicate_index_if_exists(apps, schema_editor):
    """Drop the duplicate LIKE index if it exists before making slug unique."""
    with connection.cursor() as cursor:
        # Drop all possible variations of the index
        index_names = [
            'inventory_product_slug_40cd5b78_like',
            'inventory_product_slug_like',
        ]
        for index_name in index_names:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE schemaname = 'public' AND indexname = %s
            """, [index_name])
            if cursor.fetchone():
                try:
                    cursor.execute(f'DROP INDEX IF EXISTS {index_name};')
                    print(f"Dropped duplicate index: {index_name}")
                except Exception as e:
                    print(f"Could not drop index {index_name}: {e}")
        
        # Also drop any LIKE indexes on the slug column
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE schemaname = 'public' 
            AND tablename = 'inventory_product' 
            AND indexname LIKE '%slug%like%'
        """)
        for row in cursor.fetchall():
            index_name = row[0]
            try:
                cursor.execute(f'DROP INDEX IF EXISTS {index_name};')
                print(f"Dropped LIKE index: {index_name}")
            except Exception as e:
                print(f"Could not drop index {index_name}: {e}")


def reverse_drop_index(apps, schema_editor):
    """Reverse operation - no-op since we can't recreate the exact index."""
    pass


class Migration(migrations.Migration):
    # Make migration non-atomic to allow index operations in separate transactions
    atomic = False

    dependencies = [
        ('inventory', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'premium', 'bestseller', 'new')", max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether product is published (visible on e-commerce site)'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Extended product description for detailed content'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (150-160 chars recommended)', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (50-60 chars recommended)', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing image (Open Graph)', null=True, upload_to='og_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of key features/highlights (bullet points)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video_file',
            field=models.FileField(blank=True, help_text='Upload product video file', null=True, upload_to='product_videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video_url',
            field=models.URLField(blank=True, help_text='Link to product video (YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
        # Add slug field without unique constraint first
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated from product_name if not provided)', max_length=255),
        ),
        # Generate slugs for existing products
        migrations.RunPython(generate_slugs_for_products, reverse_generate_slugs),
        # Drop duplicate index if it exists (handles partial migration scenarios)
        # This must run before AlterField to prevent duplicate index error
        migrations.RunPython(drop_duplicate_index_if_exists, reverse_drop_index),
        # Drop the LIKE index using raw SQL (must be in separate operation for non-atomic migration)
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS inventory_product_slug_40cd5b78_like;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Now make slug unique - Django will create the proper unique constraint and index
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, help_text='URL-friendly slug (auto-generated from product_name if not provided)', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Required for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which images should be displayed (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for organizing and categorizing products', related_name='products', to='inventory.tag'),
        ),
    ]
