# Generated by Django 5.2.7 on 2025-11-05 06:21

from django.db import migrations, models, connection
from django.db.migrations.operations import SeparateDatabaseAndState
from django.utils.text import slugify


def generate_slugs_for_products(apps, schema_editor):
    """Generate unique slugs for existing products."""
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if not product.slug and product.product_name:
            base_slug = slugify(product.product_name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save(update_fields=['slug'])


def reverse_generate_slugs(apps, schema_editor):
    """Reverse migration - clear slugs."""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.all().update(slug='')




class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0005_auditlog'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle partial migrations gracefully
        # Database: Create table conditionally if it doesn't exist
        # State: Update Django's migration state to reflect Tag model exists
        SeparateDatabaseAndState(
            database_operations=[
                # Create Tag table only if it doesn't exist (handles partial migrations)
                migrations.RunSQL(
                    sql="""
                        -- Create Tag table only if it doesn't exist
                        CREATE TABLE IF NOT EXISTS inventory_tag (
                            id BIGSERIAL NOT NULL PRIMARY KEY,
                            name VARCHAR(50) NOT NULL,
                            slug VARCHAR(50) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            CONSTRAINT inventory_tag_name_key UNIQUE (name),
                            CONSTRAINT inventory_tag_slug_key UNIQUE (slug)
                        );
                        -- Create index for ordering if it doesn't exist
                        CREATE INDEX IF NOT EXISTS inventory_tag_name_idx ON inventory_tag(name);
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS inventory_tag;
                    """,
                ),
            ],
            state_operations=[
                # Update Django's migration state to reflect Tag model exists
                migrations.CreateModel(
                    name='Tag',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text="Tag name (e.g., 'premium', 'bestseller', 'new')", max_length=50, unique=True)),
                        ('slug', models.SlugField(help_text='URL-friendly slug', unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether product is published (visible on e-commerce site)'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Extended product description for detailed content'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (150-160 chars recommended)', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (50-60 chars recommended)', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social sharing image (Open Graph)', null=True, upload_to='og_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of key features/highlights (bullet points)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video_file',
            field=models.FileField(blank=True, help_text='Upload product video file', null=True, upload_to='product_videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video_url',
            field=models.URLField(blank=True, help_text='Link to product video (YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
        # Add slug field without unique constraint first
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated from product_name if not provided)', max_length=255),
        ),
        # Generate slugs for existing products
        migrations.RunPython(generate_slugs_for_products, reverse_generate_slugs),
        # Safely make slug unique using SQL (handles existing constraints/indexes gracefully)
        migrations.RunSQL(
            sql="""
                -- Drop any conflicting LIKE indexes
                DO $$
                DECLARE
                    idx_name text;
                BEGIN
                    FOR idx_name IN 
                        SELECT indexname FROM pg_indexes 
                        WHERE schemaname = 'public' 
                        AND tablename = 'inventory_product' 
                        AND indexname LIKE '%slug%like%'
                    LOOP
                        EXECUTE format('DROP INDEX IF EXISTS %I', idx_name);
                    END LOOP;
                END $$;
                
                -- Add unique constraint if it doesn't exist
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conrelid = 'inventory_product'::regclass 
                        AND conname = 'inventory_product_slug_key'
                    ) THEN
                        ALTER TABLE inventory_product 
                        ADD CONSTRAINT inventory_product_slug_key UNIQUE (slug);
                    END IF;
                END $$;
                
                -- Ensure there's an index on slug (for performance)
                CREATE INDEX IF NOT EXISTS inventory_product_slug_idx ON inventory_product(slug);
            """,
            reverse_sql="""
                ALTER TABLE inventory_product DROP CONSTRAINT IF EXISTS inventory_product_slug_key;
                DROP INDEX IF EXISTS inventory_product_slug_idx;
            """,
        ),
        # Update Django's migration state to reflect slug is unique
        # This is safe because the constraint is already added by RunSQL above
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, help_text='URL-friendly slug (auto-generated from product_name if not provided)', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Required for SEO and accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which images should be displayed (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for organizing and categorizing products', related_name='products', to='inventory.tag'),
        ),
    ]
