# Generated by Django 5.2.7 on 2025-11-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_tag_alter_productimage_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('ecommerce_domain', models.CharField(blank=True, help_text="Domain for this brand's e-commerce site", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('lead_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Order Created'), ('CLOSED', 'Closed - No Sale'), ('EXPIRED', 'Expired - No Response')], default='NEW', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('salesperson_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Any notes from customer during submission')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of lead creation', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='is_global_admin',
            field=models.BooleanField(default=False, help_text='If True, admin can access all brands'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_lead_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='available_online',
            field=models.BooleanField(default=True, help_text='Whether this unit can be purchased online'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('WALK_IN', 'Walk-in Sale'), ('ONLINE', 'Online Lead')], default='WALK_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If True, product is available to all brands regardless of brand assignment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Ordering User'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='inventory_c_phone_cc89f4_idx'),
        ),
        migrations.AddField(
            model_name='admin',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands this admin can access', related_name='admins', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands this unit is available for. Empty = inherits from product or all brands.', related_name='inventory_units', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands this product is available for. Empty = all brands.', related_name='products', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='inventory_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryunit'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='inventory.admin'),
        ),
        migrations.AddField(
            model_name='lead',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lead'),
        ),
        migrations.AddField(
            model_name='leaditem',
            name='inventory_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_items', to='inventory.inventoryunit'),
        ),
        migrations.AddField(
            model_name='leaditem',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.lead'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'inventory_unit')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['brand', 'status'], name='inventory_l_brand_i_62a374_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['customer_phone', 'brand'], name='inventory_l_custome_27da4b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'expires_at'], name='inventory_l_status_cb9a57_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'brand'], name='inventory_c_session_35c90c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer_phone', 'brand'], name='inventory_c_custome_4469b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaditem',
            unique_together={('lead', 'inventory_unit')},
        ),
    ]
