# Generated by Django 5.2.7 on 2025-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryunit_quantity_inventoryunitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity: 1 for Phones/Laptops/Tablets (unique units). Required and can be > 1 for Accessories (no unique identifier).'),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Required for Phones/Laptops/Tablets. Not used for Accessories.', max_length=100, null=True, unique=True),
        ),
    ]
