# Generated by Django 5.2.7 on 2025-10-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryunit_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file from your device (max 100MB)', null=True, upload_to='review_videos/%Y/%m/', verbose_name='Review Video File'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.customer', verbose_name='Review Creator'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link to a video (Google Drive, YouTube, etc.). If both file and URL are provided, URL takes precedence.', max_length=500, null=True, verbose_name='Review Video Link'),
        ),
    ]
