# Generated by Django 5.2.7 on 2025-11-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_brand_cart_cartitem_lead_leaditem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(help_text='Banner image for promotion', upload_to='promotions/%Y/%m/')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 20.00 for 20%)', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product_types', models.CharField(blank=True, choices=[('PH', 'Phone'), ('LT', 'Laptop'), ('TB', 'Tablet/iPad'), ('AC', 'Accessory')], help_text='All products of this type (if specified, applies to all products of this type)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='inventory.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to='inventory.admin')),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products this promotion applies to', related_name='promotions', to='inventory.product')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['brand', 'is_active', 'start_date', 'end_date'], name='inventory_p_brand_i_fd8075_idx')],
            },
        ),
    ]
