# Generated by Django 5.2.7 on 2025-11-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RA', 'Reservation Approved'), ('RR', 'Reservation Rejected'), ('RE', 'Reservation Expired'), ('TA', 'Return Approved'), ('TR', 'Return Rejected'), ('FA', 'Transfer Approved'), ('FR', 'Transfer Rejected'), ('OC', 'Order Created'), ('UR', 'Unit Reserved'), ('RP', 'Request Pending Approval'), ('NL', 'New Lead')], max_length=2),
        ),
    ]
