# Generated by Django 5.2.7 on 2025-11-01 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0008_review_video_file_alter_review_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SP', 'Salesperson'), ('IM', 'Inventory Manager'), ('CC', 'Content Creator'), ('OM', 'Order Manager')], max_length=2, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reserved this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_units', to='inventory.admin'),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='Expiration date for reservation (2 days from approval)', null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='admins', to='inventory.adminrole'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RA', 'Reservation Approved'), ('RR', 'Reservation Rejected'), ('RE', 'Reservation Expired'), ('TA', 'Return Approved'), ('TR', 'Return Rejected'), ('FA', 'Transfer Approved'), ('FR', 'Transfer Rejected'), ('OC', 'Order Created'), ('RP', 'Request Pending Approval')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=2)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from salesperson')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_return_requests', to='inventory.admin')),
                ('inventory_units', models.ManyToManyField(help_text='Units to be returned (can be multiple)', related_name='return_requests', to='inventory.inventoryunit')),
                ('requesting_salesperson', models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='inventory.admin')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=2)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='inventory.admin')),
                ('from_salesperson', models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.admin')),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.inventoryunit')),
                ('to_salesperson', models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.admin')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('EX', 'Expired')], default='PE', max_length=2)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-set to 2 days after approval', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from salesperson')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'IM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservation_requests', to='inventory.admin')),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='inventory.inventoryunit')),
                ('requesting_salesperson', models.ForeignKey(limit_choices_to={'roles__name': 'SP'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='inventory.admin')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('inventory_unit', 'requesting_salesperson', 'status')},
            },
        ),
    ]
