# Generated by Django 5.2.7 on 2025-11-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
