# Generated by Django 5.2.7 on 2025-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_make_cart_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(choices=[('SP', 'Salesperson'), ('IM', 'Inventory Manager'), ('CC', 'Content Creator'), ('OM', 'Order Manager'), ('MM', 'Marketing Manager')], db_column='role_code', max_length=2, unique=True),
        ),
    ]
