# Generated by Django 5.2.7 on 2025-11-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_marketing_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Special Offer', 'Flash Sale')", max_length=50, unique=True)),
                ('code', models.CharField(help_text="Short code (e.g., 'SO', 'FS')", max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this promotion type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type is available for use')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion Type',
                'verbose_name_plural': 'Promotion Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='display_locations',
            field=models.JSONField(default=list, help_text="List of display locations: 'stories_carousel', 'special_offers', 'flash_sales'"),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_code',
            field=models.CharField(blank=True, help_text='Auto-generated promotion code (editable)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for promotion (required for Stories Carousel)', null=True, upload_to='promotions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.ForeignKey(blank=True, help_text='Type of promotion (Special Offer, Flash Sale, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='inventory.promotiontype'),
        ),
    ]
