# Generated by Django 5.2.7 on 2025-11-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_reservationrequest_returned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Promotion applied to this item (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.promotion'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of adding to cart (promotion price or selling_price)', max_digits=10, null=True),
        ),
    ]
