# Generated by Django 5.2.7 on 2025-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_many_to_many_units_to_reservation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='sale_status',
            field=models.CharField(choices=[('AV', 'Available'), ('SD', 'Sold'), ('RS', 'Reserved'), ('RT', 'Returned'), ('PP', 'Pending Payment')], default='AV', max_length=2),
        ),
    ]
