# Generated by Django 5.2.7 on 2025-11-18 10:20

from django.db import migrations, models


def migrate_shipped_to_paid(apps, schema_editor):
    """Migrate existing SHIPPED orders to PAID status."""
    Order = apps.get_model('inventory', 'Order')
    # Update any orders with 'Shipped' status to 'Paid'
    # (SHIPPED implies payment was confirmed, so they should be PAID)
    Order.objects.filter(status='Shipped').update(status='Paid')


def reverse_migrate_paid_to_shipped(apps, schema_editor):
    """Reverse migration: convert PAID orders back to SHIPPED."""
    Order = apps.get_model('inventory', 'Order')
    # Convert PAID orders back to Shipped (for rollback)
    Order.objects.filter(status='Paid').update(status='Shipped')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_pending_payment_status'),
    ]

    operations = [
        # Data migration: convert SHIPPED to PAID before schema change
        migrations.RunPython(migrate_shipped_to_paid, reverse_migrate_paid_to_shipped),
        # Schema migration: update status choices
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
