# Generated by Django 5.2.7 on 2025-11-21 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_update_order_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='battery_mah',
            field=models.PositiveIntegerField(blank=True, help_text='Battery capacity in mAh', null=True),
        ),
        migrations.AddField(
            model_name='inventoryunitimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color variant shown in this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_images', to='inventory.color'),
        ),
    ]
