# Generated by Django 5.2.7 on 2025-12-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_battery_and_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by_products', to='inventory.product', verbose_name='Accessory Item Template'),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_accessories', to='inventory.product', verbose_name='Product Template'),
        ),
    ]
