# Generated by Django 5.2.7 on 2025-12-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_allow_all_product_types_for_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('phone_number', models.CharField(help_text='Customer phone number (2547XXXXXXXX)', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount received (for partial payments)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'STK Push Sent'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'STK Push Expired'), ('TIMEOUT', 'Payment Timeout'), ('PARTIAL', 'Partial Payment'), ('API_DOWN', 'M-Pesa API Unavailable'), ('CALLBACK_MISSED', 'Callback Not Received')], default='PENDING', max_length=20)),
                ('failure_reason', models.CharField(choices=[('NONE', 'No failure'), ('INSUFFICIENT_BALANCE', 'Insufficient balance'), ('USER_CANCELLED', 'User cancelled'), ('INVALID_PHONE', 'Invalid phone number'), ('API_ERROR', 'M-Pesa API error'), ('API_DOWNTIME', 'M-Pesa API downtime'), ('NETWORK_ERROR', 'Network error'), ('NETWORK_TIMEOUT', 'Network timeout'), ('TIMEOUT', 'Payment timeout'), ('DUPLICATE', 'Duplicate transaction'), ('EXPIRED', 'STK Push expired'), ('CALLBACK_MISSED', 'Webhook callback not received'), ('PARTIAL_PAYMENT', 'Partial payment received'), ('UNKNOWN', 'Unknown error')], default='NONE', max_length=30)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('is_retry', models.BooleanField(default=False)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('max_verification_attempts', models.IntegerField(default=5)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('api_request_data', models.JSONField(blank=True, default=dict)),
                ('api_response_data', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, choices=[('CALLBACK', 'Webhook Callback'), ('QUERY', 'API Query'), ('MANUAL', 'Manual Verification')], max_length=20, null=True)),
                ('api_downtime_detected', models.BooleanField(default=False)),
                ('network_errors', models.IntegerField(default=0)),
                ('last_api_error', models.TextField(blank=True)),
                ('last_network_error', models.TextField(blank=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('callback_retry_count', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='inventory.order')),
                ('original_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='inventory.mpesapayment')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('conversation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Refund Initiated'), ('COMPLETED', 'Refund Completed'), ('FAILED', 'Refund Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('refund_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
                ('api_response_data', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_refunds', to='inventory.order')),
                ('original_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='inventory.mpesapayment')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('PAYMENT_TIMEOUT', 'Payment Timeout')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to='inventory.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.mpesapayment')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.mpesarefund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['merchant_request_id'], name='inventory_m_merchan_2ddce5_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['checkout_request_id'], name='inventory_m_checkou_9b0fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['mpesa_receipt_number'], name='inventory_m_mpesa_r_2c24b5_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status'], name='inventory_m_status_9df542_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['order', 'status'], name='inventory_m_order_i_c55b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['phone_number'], name='inventory_m_phone_n_c67b86_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status', 'initiated_at'], name='inventory_m_status_d12c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['callback_received', 'status'], name='inventory_m_callbac_a266ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesarefund',
            index=models.Index(fields=['transaction_id'], name='inventory_m_transac_e47d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesarefund',
            index=models.Index(fields=['conversation_id'], name='inventory_m_convers_d55019_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesarefund',
            index=models.Index(fields=['status'], name='inventory_m_status_2234f6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['status'], name='inventory_p_status_fbefbe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['notification_type'], name='inventory_p_notific_bf52e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['order'], name='inventory_p_order_i_d12e36_idx'),
        ),
    ]
