# Generated by Django 5.2.7 on 2025-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_replace_mpesa_with_pesapal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pesapal Configuration',
                'verbose_name_plural': 'Pesapal Configurations',
                'ordering': ['key'],
            },
        ),
    ]
