# Generated by Django 5.2.7 on 2025-12-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_pesapalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt number (e.g., SL_1121)', max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file', null=True, upload_to='receipts/%Y/%m/')),
                ('html_content', models.TextField(blank=True, help_text='HTML content of the receipt')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='PesapalConfiguration',
        ),
        migrations.RemoveIndex(
            model_name='paymentnotification',
            name='inventory_p_status_fbefbe_idx',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='subject',
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='inventory.order', verbose_name='Related Order'),
        ),
    ]
