# Generated by Django 5.2.7 on 2026-01-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_carousel_position'),
        ('inventory', '0023_receipt_delete_pesapalconfiguration_and_more'),
    ]

    operations = [
    ]
