# Generated by Django 5.2.7 on 2026-01-03 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_merge_20260102_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='carousel_position',
            field=models.IntegerField(blank=True, help_text='Position in stories carousel (1-5). 1 = Large banner, 2-5 = Grid positions', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
