# Generated by Django 5.2.7 on 2026-01-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_receipt_whatsapp_sent_receipt_whatsapp_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='requesting_salesperson',
            field=models.ForeignKey(blank=True, help_text='Salesperson requesting return. Null for buyback units (auto-created).', limit_choices_to={'roles__name': 'SP'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='inventory.admin', verbose_name='Requesting Salesperson'),
        ),
    ]
