# Generated by Django 5.2.7 on 2026-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_review_image_condition_purchase_date'),
        ('inventory', '0027_add_idempotency_key_to_order'),
    ]

    operations = [
    ]
