# Generated by Django 5.2.7 on 2026-01-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_merge_20260116_1648'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['product_template', 'sale_status', 'available_online'], name='inventory_i_product_934f95_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['product_template', 'available_online'], name='inventory_i_product_4218a6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['sale_status'], name='inventory_i_sale_st_eff111_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['available_online'], name='inventory_i_availab_7286fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_discontinued'], name='inventory_p_is_publ_9d9a98_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'),
        ),
    ]
