# Generated by Django 5.2.7 on 2026-01-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_inventoryunit_inventory_i_product_934f95_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='inventory_p_product_d9a757_idx'),
        ),
    ]
