# Generated by Django 5.2.7 on 2026-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_cartitem_bundle_group_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bundle',
            new_name='inventory_b_brand_i_4a3eb3_idx',
            old_name='inventory_b_brand_i_4dd7a8_idx',
        ),
        migrations.RenameIndex(
            model_name='bundle',
            new_name='inventory_b_main_pr_d5dcb0_idx',
            old_name='inventory_b_main_p_58d3be_idx',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Required for Phones/Laptops/Tablets. Optional for Accessories.', max_length=100, null=True, unique=True),
        ),
    ]
