# Generated by Django 5.2.7 on 2026-01-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_rename_inventory_b_brand_i_4dd7a8_idx_inventory_b_brand_i_4a3eb3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaditem',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Bundle applied to this lead item (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_items', to='inventory.bundle'),
        ),
        migrations.AddField(
            model_name='leaditem',
            name='bundle_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups lead items added as a single bundle', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Bundle applied to this order item (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.bundle'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bundle_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups order items added as a single bundle', null=True),
        ),
    ]
