# Generated by Django 5.2.7 on 2026-02-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_delivery_rates_and_scheduling'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryrate',
            new_name='inventory_d_county_90ab50_idx',
            old_name='inventory_d_county_ward_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryrate',
            new_name='inventory_d_is_acti_f64daf_idx',
            old_name='inventory_d_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='inventory_w_session_e05b6f_idx',
            old_name='inventory_w_session__b3f1e6_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='inventory_w_custome_9c3a50_idx',
            old_name='inventory_w_customer_e9d9df_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='inventory_w_product_45611f_idx',
            old_name='inventory_w_product_5d2f2e_idx',
        ),
    ]
