# Generated by Django 5.2.7 on 2026-02-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_customer_email_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
