# Generated by Django 5.2.7 on 2026-02-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_inventoryunitimage_image_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaccessory',
            options={'ordering': ['id']},
        ),
    ]
