# Generated by Django 5.2.7 on 2026-03-18 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_promotion_featured_product_and_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='carousel_position',
            field=models.IntegerField(blank=True, help_text='Display order in carousels (e.g. homepage hero). Any positive integer; lower = earlier.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='display_locations',
            field=models.JSONField(default=list, help_text="List of display locations: 'stories_carousel', 'special_offers', 'flash_sales', 'homepage_hero'"),
        ),
    ]
