# Generated by Django 5.2.7 on 2026-03-27 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_unique_product_brand_model_series_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financing/providers/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('retail_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_payment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_payment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('rom_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_offers', to='inventory.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='inventory.financingprovider')),
            ],
            options={
                'ordering': ['provider__name', 'product_id', 'rom_gb', 'ram_gb', 'id'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='inventory_f_provide_dba7c9_idx'), models.Index(fields=['product', 'is_active'], name='inventory_f_product_86b180_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'product', 'ram_gb', 'rom_gb'), name='uniq_financing_offer_provider_product_ram_rom')],
            },
        ),
    ]
