# Generated by Cursor on 2026-04-22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_financingprovider_financingoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financingoffer",
            name="daily_payment",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="financingoffer",
            name="weekly_payment",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="financingoffer",
            name="monthly_payment",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]

