# Generated by Django 5.2.7 on 2026-05-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_financingoffer_term_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArticle',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='article', serialize=False, to='inventory.product')),
                ('headline', models.CharField(blank=True, help_text='Public H1 for the article page', max_length=255)),
                ('seo_title', models.CharField(blank=True, help_text='Article page title tag (50–60 chars recommended)', max_length=60)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description (150–160 chars recommended)', max_length=160)),
                ('body', models.TextField(blank=True, help_text='Article body (Markdown)')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
                'indexes': [models.Index(fields=['is_published'], name='inventory_p_is_publ_d13a70_idx')],
            },
        ),
    ]
