# Generated by Django 5.2.7 on 2026-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shown on the storefront when no online/listable units have a price; used when creating a unit if selling price is omitted.', max_digits=10, null=True, verbose_name='Default selling price'),
        ),
    ]
