# Generated by Django 5.2.7 on 2026-05-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_seed_default_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productarticle',
            name='body',
            field=models.TextField(blank=True, help_text='Article body (HTML from rich text editor)'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Required for SEO and accessibility', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=500)),
                ('position', models.IntegerField(default=0, help_text='Order in which images should be displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.productarticle')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['article'], name='inventory_a_article_16243c_idx')],
            },
        ),
    ]
