# Generated by Django 5.2.7 on 2026-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_article_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productarticle',
            name='category',
            field=models.CharField(choices=[('buying_guide', 'Buying Guide'), ('tech_tip', 'Tech Tip'), ('news', 'News'), ('general', 'General')], default='buying_guide', max_length=50),
        ),
        migrations.AddField(
            model_name='productarticle',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Featured image for blog lists and social sharing', null=True, upload_to='article_thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productarticle',
            name='body',
            field=models.TextField(blank=True, help_text='Article body (Markdown supported)'),
        ),
        migrations.AlterField(
            model_name='productarticle',
            name='headline',
            field=models.CharField(blank=True, help_text="Public H1 for the article page (e.g. 'Galaxy A42 5G in Kenya: who should buy it?')", max_length=255),
        ),
        migrations.AlterField(
            model_name='productarticle',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published on storefront'),
        ),
    ]
