# Generated by Django 5.2.7 on 2026-05-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_cartitem_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(default='AFFORDABLE_GADGETS', max_length=50)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product clicked')),
            ],
            options={
                'verbose_name': 'WhatsApp Click Event',
                'verbose_name_plural': 'WhatsApp Click Events',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
