# Generated by Django 5.2.7 on 2026-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_productarticle_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Supabase User ID'),
        ),
        migrations.AddField(
            model_name='whatsappclickevent',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='User email'),
        ),
        migrations.AddField(
            model_name='whatsappclickevent',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='User phone'),
        ),
    ]
