# Generated by Django 5.2.7 on 2026-06-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0067_productarticle_id_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_gb", models.PositiveIntegerField(blank=True, null=True)),
                ("ram_gb", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "default_selling_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "default_cost_of_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variant is available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product", "storage_gb", "ram_gb"],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="inventoryunit",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Product variant this unit was created from (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_units",
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Product variant ordered (before InventoryUnit is assigned at fulfillment).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "storage_gb", "ram_gb")},
        ),
    ]
