# Generated by Django 5.2.7 on 2026-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_product_variant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram_gb',
            field=models.IntegerField(blank=True, help_text='RAM in GB (e.g., 4, 8, 12, 16)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_gb',
            field=models.IntegerField(blank=True, help_text='Storage capacity in GB (e.g., 128, 256, 512)', null=True),
        ),
    ]
