# Generated by Django 5.2.7 on 2026-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_productarticletombstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for filtering featured product blogs (e.g. featured, trending)', related_name='articles', to='inventory.tag'),
        ),
    ]
