# Generated by Django 5.2.7 on 2026-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_productvideo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productarticle',
            new_name='inventory_p_slug_87edaa_idx',
            old_name='inventory_p_slug_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='productarticleslugredirect',
            new_name='inventory_p_article_4de459_idx',
            old_name='inventory_p_article_0c8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='productarticletombstone',
            new_name='inventory_p_slug_0cba31_idx',
            old_name='inventory_p_slug_7f1c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='productslugredirect',
            new_name='inventory_p_product_50c048_idx',
            old_name='inventory_p_product_4d2f0a_idx',
        ),
        migrations.AddField(
            model_name='promotion',
            name='listing_brand',
            field=models.CharField(blank=True, default='', help_text='Product brand filter for brand_banner (e.g. Apple, Samsung). Matches /products?brand_filter=…', max_length=64),
        ),
        migrations.AlterField(
            model_name='observabilityevent',
            name='event_type',
            field=models.CharField(choices=[('search', 'Search Query'), ('product_view', 'Product Detail View'), ('page_view', 'Page View'), ('whatsapp_click', 'WhatsApp Click'), ('cart_add', 'Add to Cart'), ('login', 'Login')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='display_locations',
            field=models.JSONField(default=list, help_text="List of display locations: 'stories_carousel', 'special_offers', 'flash_sales', 'homepage_hero', 'cbd_ribbon', 'brand_banner'"),
        ),
    ]
