# Generated by Django 5.2.7 on 2026-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_productvideo'),
    ]

    operations = [
        # Note: auto-generated RenameIndex ops were removed — they referenced
        # historical index names that do not exist on a clean migrate (CI) and
        # are unrelated to listing_brand / brand_banner.
        migrations.AddField(
            model_name='promotion',
            name='listing_brand',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Product brand filter for brand_banner (e.g. Apple, Samsung). Matches /products?brand_filter=…',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='observabilityevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('search', 'Search Query'),
                    ('product_view', 'Product Detail View'),
                    ('page_view', 'Page View'),
                    ('whatsapp_click', 'WhatsApp Click'),
                    ('cart_add', 'Add to Cart'),
                    ('login', 'Login'),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='display_locations',
            field=models.JSONField(
                default=list,
                help_text="List of display locations: 'stories_carousel', 'special_offers', 'flash_sales', 'homepage_hero', 'cbd_ribbon', 'brand_banner'",
            ),
        ),
    ]
