---
- name: Deploy Prometheus + Grafana on AWS monitoring EC2
  hosts: monitoring
  become: true
  vars_files:
    - ../group_vars/all/00_system.yml
    - ../group_vars/production.yml
    - ../vars/generated_from_terraform.yml
    - ../secrets/production.vault.yml
  roles:
    - common
    - monitoring_compose
