"""
Daily KPI Report Generator.
Runs on the monitoring VM, queries Prometheus, outputs HTML report to stdout.
"""
import json
import urllib.request
import datetime

PROMETHEUS = "http://localhost:9090"

def promql(query):
    url = f"{PROMETHEUS}/api/v1/query?query={urllib.request.quote(query)}"
    try:
        resp = urllib.request.urlopen(url, timeout=10).read()
        d = json.loads(resp)
        return d.get("data", {}).get("result", [])
    except Exception:
        return []

def val(metric, agg="max"):
    r = promql(f"{agg}({metric}) or vector(0)")
    return r[0]["value"][1] if r else "0"

def val_inc(metric, period="24h"):
    r = promql(f"sum(increase({metric}[{period}])) or vector(0)")
    return r[0]["value"][1] if r else "0"

def val_with_labels(metric, agg="max", label="brand"):
    r = promql(f"{agg}({metric}) by ({label}) or vector(0)")
    items = {}
    for s in r:
        items[s["metric"].get(label, "?")] = s["value"][1]
    return items

today = datetime.date.today().isoformat()

rev_24h = val_inc("revenue_earned_cumulative")
orders_24h = val_inc("orders_created_cumulative")
leads_24h = val_inc("leads_created_cumulative")
conv_24h = val_inc("leads_converted_cumulative")
cust_24h = val_inc("customers_registered_cumulative")
try:
    lead_rate = f"{round(float(conv_24h) / max(float(leads_24h), 1) * 100, 1)}%"
except:
    lead_rate = "0%"

active_carts = val("cart_active_carts")
stale_carts = val("cart_stale_carts")
inventory = val("inventory_value_total{status=\"AV\"}")
carts_total = val("carts_total{status=\"total\"}")
customers = val("customers_total")
app_instances = val("app_instances_active")
active_users = val("active_users")

popular = promql("sort_desc(max(cart_popular_items) by (product_name))")
popular_items = []
for s in popular[:5]:
    popular_items.append((s["metric"].get("product_name","?"), s["value"][1]))

orders_by_status = val_with_labels("orders_by_status", agg="max", label="status")

html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Affordable Gadgets — Daily KPI Report</title></head>
<body style="font-family:system-ui,sans-serif;max-width:700px;margin:0 auto;">
<h1>KPI Report — {today}</h1>

<h2>Period Metrics (24h change)</h2>
<table style="width:100%;border-collapse:collapse;">
<tr style="background:#f3f4f6;"><th>Metric</th><th>Value</th></tr>
<tr><td>Revenue (24h)</td><td>{rev_24h} KES</td></tr>
<tr><td>Orders Created (Net, 24h)</td><td>{orders_24h}</td></tr>
<tr><td>New Leads (24h)</td><td>{leads_24h}</td></tr>
<tr><td>Conversions (24h)</td><td>{conv_24h}</td></tr>
<tr><td>New Customers (24h)</td><td>{cust_24h}</td></tr>
<tr><td>Lead Conv. Rate (24h)</td><td>{lead_rate}</td></tr>
</table>

<h2>Current State</h2>
<table style="width:100%;border-collapse:collapse;">
<tr style="background:#f3f4f6;"><th>Metric</th><th>Value</th></tr>
<tr><td>Active Carts</td><td>{active_carts}</td></tr>
<tr><td>Stale Carts (>2h)</td><td>{stale_carts}</td></tr>
<tr><td>Total Carts (All Time)</td><td>{carts_total}</td></tr>
<tr><td>Inventory Value (AV)</td><td>{inventory} KES</td></tr>
<tr><td>Customers</td><td>{customers}</td></tr>
<tr><td>Active Users</td><td>{active_users}</td></tr>
<tr><td>App Instances</td><td>{app_instances}</td></tr>
</table>

<h2>Orders by Status</h2>
<table style="width:100%;border-collapse:collapse;">
<tr style="background:#f3f4f6;"><th>Status</th><th>Count</th></tr>
"""
for st, cnt in orders_by_status.items():
    html += f"<tr><td>{st}</td><td>{cnt}</td></tr>\n"

html += """</table>

<h2>Top Items in Active Carts</h2>
<table style="width:100%;border-collapse:collapse;">
<tr style="background:#f3f4f6;"><th>Product</th><th>Count</th></tr>
"""
for name, cnt in popular_items:
    html += f"<tr><td>{name}</td><td>{cnt}</td></tr>\n"

html += """</table>

<hr>
<p style="color:#6b7280;font-size:small;">
Generated by <code>daily-kpi-report.py</code> from Prometheus data.
</p>
</body></html>"""

print(html)
