---
all:
  children:
    bastion:
      hosts:
        bastion-01:
          ansible_host: bastion-production
    tunnel:
      hosts:
        tunnel-01:
          ansible_host: tunnel-production
    api:
      hosts: {}
    shop:
      hosts: {}
    admin:
      hosts: {}
    monitoring:
      hosts:
        monitoring-01:
          ansible_host: 127.0.0.1
