"""Import products and variants from the stock-list CSV pair.

Reads ``inventory/data/stock_list_2026_06_19_products.csv`` and
``inventory/data/stock_list_2026_06_19_variants.csv`` (generated by
``scripts/build_stock_list_csv.py``).

Idempotent:
- Products matched by ``product_name`` (or ``brand`` + ``model_series`` + ``product_type``)
- Variants matched by ``(product, storage_gb, ram_gb)`` — prices updated on re-run

Usage::

    python scripts/build_stock_list_csv.py
    python manage.py import_stock_list --dry-run
    python manage.py import_stock_list
    python manage.py import_stock_list --overwrite-existing-prices

After a full import, generic legacy Apple rows (e.g. plain ``iPhone 17``) are
unpublished when E-SIM / SIM stock-list products exist — pass
``--skip-unpublish-superseded`` to disable.
"""

from __future__ import annotations

import csv
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from inventory.models import Product, ProductVariant

User = get_user_model()

DATA_DIR = Path(__file__).resolve().parents[2] / "data"
DEFAULT_PRODUCTS_CSV = DATA_DIR / "stock_list_2026_06_19_products.csv"
DEFAULT_VARIANTS_CSV = DATA_DIR / "stock_list_2026_06_19_variants.csv"

VALID_PRODUCT_TYPES = {choice[0] for choice in Product.ProductType.choices}


def _parse_bool(value: Any, default: bool = True) -> bool:
    if value is None:
        return default
    s = str(value).strip().lower()
    if s in ("true", "1", "yes", "y"):
        return True
    if s in ("false", "0", "no", "n", ""):
        return False
    return default


def _parse_int(value: Any) -> int | None:
    if value is None:
        return None
    s = str(value).strip()
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def _parse_decimal(value: Any) -> Decimal | None:
    if value is None:
        return None
    s = str(value).strip().replace(",", "")
    if not s:
        return None
    try:
        return Decimal(s)
    except (InvalidOperation, ValueError):
        return None


class Command(BaseCommand):
    help = "Import products and variants from stock-list CSV files."

    def add_arguments(self, parser):
        parser.add_argument(
            "--products-csv",
            type=str,
            default=str(DEFAULT_PRODUCTS_CSV),
            help=f"Products CSV (default: {DEFAULT_PRODUCTS_CSV})",
        )
        parser.add_argument(
            "--variants-csv",
            type=str,
            default=str(DEFAULT_VARIANTS_CSV),
            help=f"Variants CSV (default: {DEFAULT_VARIANTS_CSV})",
        )
        parser.add_argument(
            "--user",
            type=str,
            default="admin",
            help="Username for created_by / updated_by (default: admin)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show actions without writing to the database",
        )
        parser.add_argument(
            "--stop-on-error",
            action="store_true",
            help="Abort on first error (default: continue)",
        )
        parser.add_argument(
            "--no-update-prices",
            action="store_true",
            help="Skip updating prices on existing products/variants",
        )
        parser.add_argument(
            "--overwrite-existing-prices",
            action="store_true",
            help="Overwrite existing non-null prices (default: preserve set prices)",
        )
        parser.add_argument(
            "--products-only",
            action="store_true",
            help="Import products CSV only, skip variants",
        )
        parser.add_argument(
            "--variants-only",
            action="store_true",
            help="Import variants CSV only (products must already exist)",
        )
        parser.add_argument(
            "--skip-unpublish-superseded",
            action="store_true",
            help=(
                "Do not unpublish generic legacy Apple iPhone products after import "
                "(default: unpublish when E-SIM/SIM replacements exist)"
            ),
        )
        parser.add_argument(
            "--skip-sync-media",
            action="store_true",
            help=(
                "Do not copy images/blogs from similar catalog rows after import "
                "(default: run sync_stock_list_media)"
            ),
        )

    def handle(self, *args, **options):
        products_csv = Path(options["products_csv"]).expanduser()
        variants_csv = Path(options["variants_csv"]).expanduser()
        dry_run = bool(options["dry_run"])
        stop_on_error = bool(options["stop_on_error"])
        update_prices = not bool(options["no_update_prices"])
        overwrite = bool(options["overwrite_existing_prices"])
        products_only = bool(options["products_only"])
        variants_only = bool(options["variants_only"])
        skip_unpublish = bool(options["skip_unpublish_superseded"])
        skip_sync_media = bool(options["skip_sync_media"])

        if products_only and variants_only:
            raise CommandError("Cannot pass both --products-only and --variants-only.")

        created_by = None
        try:
            created_by = User.objects.get(username=options["user"])
        except User.DoesNotExist:
            self.stdout.write(
                self.style.WARNING(
                    f"User '{options['user']}' not found — records created without audit user."
                )
            )

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN — no database writes."))

        product_stats = {"created": 0, "skipped": 0, "updated": 0, "failed": 0, "invalid": 0}
        variant_stats = {
            "created": 0,
            "updated": 0,
            "skipped": 0,
            "failed": 0,
            "invalid": 0,
            "missing_product": 0,
        }

        if not variants_only:
            if not products_csv.is_file():
                raise CommandError(f"Products CSV not found: {products_csv}")
            self._import_products(
                products_csv,
                created_by,
                dry_run,
                stop_on_error,
                update_prices,
                overwrite,
                product_stats,
            )

        if not products_only:
            if not variants_csv.is_file():
                raise CommandError(f"Variants CSV not found: {variants_csv}")
            self._import_variants(
                variants_csv,
                dry_run,
                stop_on_error,
                update_prices,
                overwrite,
                variant_stats,
            )

        self.stdout.write("")
        self.stdout.write(self.style.HTTP_INFO("=== Import summary ==="))
        if not variants_only:
            self.stdout.write(
                f"Products — created: {product_stats['created']}, "
                f"skipped: {product_stats['skipped']}, "
                f"price-updated: {product_stats['updated']}, "
                f"invalid: {product_stats['invalid']}, "
                f"failed: {product_stats['failed']}"
            )
        if not products_only:
            self.stdout.write(
                f"Variants — created: {variant_stats['created']}, "
                f"updated: {variant_stats['updated']}, "
                f"skipped: {variant_stats['skipped']}, "
                f"missing product: {variant_stats['missing_product']}, "
                f"invalid: {variant_stats['invalid']}, "
                f"failed: {variant_stats['failed']}"
            )

        if not skip_unpublish and not products_only:
            from inventory.management.commands.unpublish_superseded_apple_phones import (
                unpublish_superseded_apple_phones,
            )

            self.stdout.write("")
            self.stdout.write(
                self.style.HTTP_INFO("=== Unpublish superseded generic Apple iPhones ===")
            )
            unpublish_stats = unpublish_superseded_apple_phones(dry_run=dry_run)
            for key, value in unpublish_stats.items():
                self.stdout.write(f"  {key}: {value}")

        if not skip_sync_media and not products_only:
            from inventory.management.commands.sync_stock_list_media import (
                sync_stock_list_media,
            )

            self.stdout.write("")
            self.stdout.write(self.style.HTTP_INFO("=== Sync stock-list images and blogs ==="))
            sync_stats = sync_stock_list_media(
                products_csv=products_csv,
                dry_run=dry_run,
                skip_blog_reload=False,
                stdout=self.stdout,
                style=self.style,
            )
            for key, value in sync_stats.items():
                self.stdout.write(f"  {key}: {value}")

        if dry_run:
            self.stdout.write(self.style.WARNING("(dry-run — nothing written)"))

    def _import_products(
        self,
        csv_path: Path,
        created_by,
        dry_run: bool,
        stop_on_error: bool,
        update_prices: bool,
        overwrite: bool,
        stats: dict[str, int],
    ) -> None:
        self.stdout.write(self.style.HTTP_INFO(f"Reading products: {csv_path}"))
        with csv_path.open("r", newline="", encoding="utf-8-sig") as fh:
            rows = list(csv.DictReader(fh))

        existing_by_name = {
            p.product_name: p
            for p in Product.objects.only(
                "id",
                "product_name",
                "brand",
                "model_series",
                "product_type",
                "default_selling_price",
            )
        }
        existing_by_key = {
            (p.brand, p.model_series, p.product_type): p for p in existing_by_name.values()
        }

        for idx, row in enumerate(rows, start=2):
            name = (row.get("product_name") or "").strip()
            if not name:
                stats["invalid"] += 1
                continue

            ptype = (row.get("product_type") or "").strip().upper()
            if ptype not in VALID_PRODUCT_TYPES:
                stats["invalid"] += 1
                self.stdout.write(
                    self.style.ERROR(f"Row {idx}: invalid product_type {ptype!r} for {name}")
                )
                if stop_on_error:
                    raise CommandError(f"Invalid product_type on row {idx}")
                continue

            brand = (row.get("brand") or "").strip() or "N/A"
            model_series = (row.get("model_series") or "").strip() or "N/A"
            csv_price = _parse_decimal(row.get("default_selling_price"))

            existing = existing_by_name.get(name)
            if existing is None:
                existing = existing_by_key.get((brand, model_series, ptype))
            if existing is not None:
                existing_by_name[name] = existing
                stats["skipped"] += 1
                if update_prices and csv_price is not None:
                    if existing.default_selling_price is not None and not overwrite:
                        pass
                    elif dry_run:
                        stats["updated"] += 1
                        self.stdout.write(
                            f"DRY: would update product price {name} -> {csv_price}"
                        )
                    else:
                        Product.objects.filter(pk=existing.pk).update(
                            default_selling_price=csv_price
                        )
                        stats["updated"] += 1
                continue

            payload = {
                "product_type": ptype,
                "product_name": name,
                "product_description": (row.get("product_description") or "").strip(),
                "brand": brand,
                "model_series": model_series,
                "default_selling_price": csv_price,
                "is_published": _parse_bool(row.get("is_published"), default=True),
            }
            if created_by is not None:
                payload["created_by"] = created_by
                payload["updated_by"] = created_by

            if dry_run:
                stats["created"] += 1
                self.stdout.write(f"DRY: would create product [{ptype}] {name}")
                existing_by_name[name] = Product(**payload)
                existing_by_key[(brand, model_series, ptype)] = existing_by_name[name]
                continue

            try:
                with transaction.atomic():
                    product = Product.objects.create(**payload)
                stats["created"] += 1
                existing_by_name[name] = product
                existing_by_key[(brand, model_series, ptype)] = product
                self.stdout.write(self.style.SUCCESS(f"OK  product [{ptype}] {name}"))
            except Exception as exc:  # noqa: BLE001
                stats["failed"] += 1
                self.stdout.write(self.style.ERROR(f"FAIL product {name}: {exc}"))
                if stop_on_error:
                    raise

    def _import_variants(
        self,
        csv_path: Path,
        dry_run: bool,
        stop_on_error: bool,
        update_prices: bool,
        overwrite: bool,
        stats: dict[str, int],
    ) -> None:
        self.stdout.write(self.style.HTTP_INFO(f"Reading variants: {csv_path}"))
        with csv_path.open("r", newline="", encoding="utf-8-sig") as fh:
            rows = list(csv.DictReader(fh))

        products_by_name = {p.product_name: p for p in Product.objects.all()}
        products_by_model_series = {
            p.model_series: p for p in Product.objects.all() if p.model_series
        }

        def resolve_product(csv_name: str) -> Product | None:
            product = products_by_name.get(csv_name)
            if product is not None:
                return product
            product = products_by_model_series.get(csv_name)
            if product is not None:
                return product
            prefixed = Product.objects.filter(product_name__iexact=f"Samsung {csv_name}").first()
            if prefixed is not None:
                return prefixed
            return Product.objects.filter(product_name__iendswith=csv_name).first()

        for idx, row in enumerate(rows, start=2):
            name = (row.get("product_name") or "").strip()
            if not name:
                stats["invalid"] += 1
                continue

            product = resolve_product(name)
            if product is None:
                stats["missing_product"] += 1
                self.stdout.write(
                    self.style.WARNING(f"Row {idx}: product not found: {name!r}")
                )
                continue

            storage = _parse_int(row.get("storage_gb"))
            ram = _parse_int(row.get("ram_gb"))
            sell_price = _parse_decimal(row.get("ref_sell_kes"))
            cost_price = _parse_decimal(row.get("ref_cost_kes")) or Decimal("0")
            is_active = _parse_bool(row.get("is_active"), default=True)

            if sell_price is None or sell_price <= 0:
                stats["invalid"] += 1
                self.stdout.write(
                    self.style.ERROR(f"Row {idx}: invalid ref_sell_kes for {name}")
                )
                continue

            existing = ProductVariant.objects.filter(
                product=product, storage_gb=storage, ram_gb=ram
            ).first()

            if existing is not None:
                if not update_prices:
                    stats["skipped"] += 1
                    continue
                if existing.default_selling_price is not None and not overwrite:
                    stats["skipped"] += 1
                    continue

                if dry_run:
                    stats["updated"] += 1
                    label = _variant_label(storage, ram)
                    self.stdout.write(
                        f"DRY: would update variant {name} {label} -> {sell_price}"
                    )
                    continue

                try:
                    existing.default_selling_price = sell_price
                    existing.default_cost_of_unit = cost_price
                    existing.is_active = is_active
                    existing.save(
                        update_fields=[
                            "default_selling_price",
                            "default_cost_of_unit",
                            "is_active",
                            "updated_at",
                        ]
                    )
                    stats["updated"] += 1
                except Exception as exc:  # noqa: BLE001
                    stats["failed"] += 1
                    self.stdout.write(self.style.ERROR(f"FAIL variant update {name}: {exc}"))
                    if stop_on_error:
                        raise
                continue

            if dry_run:
                stats["created"] += 1
                label = _variant_label(storage, ram)
                self.stdout.write(f"DRY: would create variant {name} {label} @ {sell_price}")
                continue

            try:
                ProductVariant.objects.create(
                    product=product,
                    storage_gb=storage,
                    ram_gb=ram,
                    default_selling_price=sell_price,
                    default_cost_of_unit=cost_price,
                    is_active=is_active,
                )
                stats["created"] += 1
                label = _variant_label(storage, ram)
                self.stdout.write(
                    self.style.SUCCESS(f"OK  variant {name} {label} @ {sell_price}")
                )
            except Exception as exc:  # noqa: BLE001
                stats["failed"] += 1
                self.stdout.write(self.style.ERROR(f"FAIL variant create {name}: {exc}"))
                if stop_on_error:
                    raise


def _variant_label(storage: int | None, ram: int | None) -> str:
    parts = []
    if storage:
        parts.append(f"{storage}GB" if storage < 1024 else f"{storage // 1024}TB")
    if ram:
        parts.append(f"{ram}GB RAM")
    return "/".join(parts) if parts else "default"
